### ISSUE TITLE
Improve privacy model

### ISSUE THREAD

**Issue by calebbourg** [Jim-Hodapp-Coaching/esp32-wroom-rp#30]
There are a number publicly exposed types that should be private. Ex. `Operation`

see [this comment](https://github.com/Jim-Hodapp-Coaching/esp32-wroom-rp/pull/29#pullrequestreview-1111463740)

**AC:** 
- All types other than `Wifi` and potentially `FirmwareVersion` are private

**Comment by jhodapp** [comment]
Rust documentation on how to accomplish this: https://doc.rust-lang.org/reference/visibility-and-privacy.html
