### ISSUE TITLE
Support the use of both IP addresses and host names for remote servers

### ISSUE THREAD

**Issue by jhodapp** [Jim-Hodapp-Coaching/esp32-wroom-rp#36]
New Feature:

* Support the use of both IP addresses and host names for remote servers

```
# initialization code
...
esp32_wroom_rp::wifi::Wifi::set_dns(Vec<ip_address>);

let ip_address = esp32_wroom_rp::wifi::Wifi::resolve(hostname);
```

Definition of Done:

* Consumers of the crate can set a DNS server to use to resolve hostnames and URLs.
* Consumers of the crate can look up an IP address by providing a hostname.
* Only IPv4 will be supported at this time for all IP addresses. IPv6 is unsupported.

**Comment by calebbourg** [comment]
@jhodapp @dilyn-corner 
In our initial interface discussion https://github.com/Jim-Hodapp-Coaching/esp32-wroom-rp/discussions/10 we had chosen the method name `resolve(hostname)` for resolving a hostname to an IP address.

The example here calls it `host_by_name(hostname)`.

Do we prefer one over the other?
Another thought might be some combination like `resolve_hostname(hostname)`.

**Comment by jhodapp** [comment]
`resolve` works for me, I had forgotten about that prior discussion.

**Comment by jhodapp** [comment]
Updated to use `resolve` instead.
