### ISSUE TITLE
Audit use of unwrap and error handling 

### ISSUE THREAD

**Issue by calebbourg** [Jim-Hodapp-Coaching/esp32-wroom-rp#54]
Prior to publishing to crates.io we should take a look at each point in the code where we use `unwrap` and determine if there is any room for improvements.
In most cases we likely would not want the code to panic and so some other policy for error handling will likely be appropriate.

**Comment by jhodapp** [comment]
[A useful overview of error handling from Rust by Example](https://doc.rust-lang.org/stable/rust-by-example/error.html).
